# 1
Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.


In [1]:
import numpy as np

# Sayılardan oluşan bir boyutlu dizi oluşturdum
bir_boyutlu_dizi = np.array([1, 2, 3, 4, 5], dtype=int)

# Dizi boyutunu kontrol ettim
boyut = bir_boyutlu_dizi.ndim

# Eleman sayısını kontrol ettim
eleman_sayısı = bir_boyutlu_dizi.size

print("Boyut:", boyut)
print("Eleman Sayısı:", eleman_sayısı)

Boyut: 1
Eleman Sayısı: 5


# 2
İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [2]:
# İki boyutlu dizi oluşturdum
iki_boyutlu_dizi = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

# Üç boyutlu dizi oluşturdum
üç_boyutlu_dizi = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=int)

# Dizilerin boyutlarını ve eleman sayılarını kontrol ettim
boyut_2d = iki_boyutlu_dizi.ndim
boyut_3d = üç_boyutlu_dizi.ndim
eleman_sayısı_2d = iki_boyutlu_dizi.size
eleman_sayısı_3d = üç_boyutlu_dizi.size

print("İki Boyutlu Dizi Boyutu:", boyut_2d)
print("İki Boyutlu Dizi Eleman Sayısı:", eleman_sayısı_2d)
print("Üç Boyutlu Dizi Boyutu:", boyut_3d)
print("Üç Boyutlu Dizi Eleman Sayısı:", eleman_sayısı_3d)

İki Boyutlu Dizi Boyutu: 2
İki Boyutlu Dizi Eleman Sayısı: 6
Üç Boyutlu Dizi Boyutu: 3
Üç Boyutlu Dizi Eleman Sayısı: 8


# 3
Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

In [3]:
# İki boyutlu dizi üzerinde indexleme
ilk_satır = iki_boyutlu_dizi[0]
ikinci_satır = iki_boyutlu_dizi[1]
birinci_eleman = iki_boyutlu_dizi[0, 0]

# İki boyutlu dizi üzerinde dilimleme
dilimleme_1 = iki_boyutlu_dizi[:, 1]  # Tüm satırlardan ikinci sütun
dilimleme_2 = iki_boyutlu_dizi[1, :]  # İkinci satırdan tüm sütunlar

print("İlk Satır:", ilk_satır)
print("İkinci Satır:", ikinci_satır)
print("Birinci Eleman:", birinci_eleman)
print("Dilimleme 1:", dilimleme_1)
print("Dilimleme 2:", dilimleme_2)

İlk Satır: [1 2 3]
İkinci Satır: [4 5 6]
Birinci Eleman: 1
Dilimleme 1: [2 5]
Dilimleme 2: [4 5 6]


# 4
Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.

In [4]:
# Sıfırlardan oluşan bir dizi oluşturdum
sıfırlar_dizisi = np.zeros((2, 3), dtype=int)

# Birlerden oluşan bir dizi oluşturdum
birler_dizisi = np.ones((2, 3), dtype=int)

# Dizileri satır bazında birleştirdim
birleştirilmiş_dizi = np.vstack((sıfırlar_dizisi, birler_dizisi))

# Dizileri sütun bazında birleştirdim
# birleştirilmiş_dizi = np.hstack((sıfırlar_dizisi, birler_dizisi)) # İsterseniz bu şekilde de birleştirebilirsiniz.

print("Sıfırlar Dizi:")
print(sıfırlar_dizisi)
print("Birler Dizi:")
print(birler_dizisi)
print("Birleştirilmiş Dizi:")
print(birleştirilmiş_dizi)


Sıfırlar Dizi:
[[0 0 0]
 [0 0 0]]
Birler Dizi:
[[1 1 1]
 [1 1 1]]
Birleştirilmiş Dizi:
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
